SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800
PADDDLE_HEIGHT = 20
PADDLE_SPEED = 10 
BLOCK_TYPES = 3
FPS = 60
BALL_RADIUS = 10
BALL_MAX_SPEED = 6
BALL_MIN_SPEED = 1
COLLIDE_TRESHOLD = 8
AIM_MIN_ANGLE = 225
AIM_MAX_ANGLE = 315
AIM_SPEED = 1
SCORE_PADDING = 5 
SCORE_LENGTH = 6
BLOCK_PADDING = 5

